### ISSUE TITLE
Use Windsor Registrations

### ISSUE THREAD

**Issue by kabudahab** [sharparchitecture/Sharp-Architecture#107]
Use Windsor Registrations (IWindsorInstaller) for registering components. 
Reference: https://github.com/carcer/RealWorldMvc

**Comment by kad0xf** [comment]
I think the web Nuget package (SharpArch.Web.Mvc.Castle) should add the installers files automatically. what do you think?

**Comment by seif** [comment]
I think it would complicate things a bit, as we would need to have Installers for Raven and for NHibernate (or whatever other data access user wants to have). We can't add the installers to the SharpArch.Raven/NHibernate nuget, as that doesn't know about castle.

I guess we could have a bunch of packages with the installers for MVC/WebApi/Raven/NHibernate. But it is a bunch of work.

**Comment by seif** [comment]
@kad0xf after discussiong, we decided that it would be better that this code is avilable in the user's code, as they would want to handle how the objects are injected and IoC setup.

**Comment by shatl** [comment]
So far I came up with helper methods for integration of Castle Windsor into ASP.NET MVC and WebAPI

**Comment by shatl** [comment]
@shatl Will update the docs with a sample

**Comment by shatl** [comment]
Will be replaced with Microsoft Dependency Injection
