### ISSUE TITLE
sharparchitecture.net is no longer valid...

### ISSUE THREAD

**Issue by Mystere** [sharparchitecture/Sharp-Architecture#112]
Seems like the sharparchitecture.net domain is no longer valid, so all links to documentation and what not are no longer valid either....

**Comment by seif** [comment]
Thanks @Mystere I knew we are going to have problems with the sharparchitecture.net as github pages moved to a new ip address, and contacting @codai to update didn't result in a change :(

What I didn't realise though is that the whole domain is gone. Not event docs.sharparchitecture.net probably best is to register a new domain sharparchitecture.org or sharparchitecture.io and relink everything, unfortunately we will loose all the search results and there is no redirect on the old stuff :(

**Comment by seif** [comment]
Mean while you can access the docs @ http://sharp-architecture.readthedocs.org/en/latest/

**Comment by seif** [comment]
Just use the github/readthedocs urls, and no custom domain.

Need to update all the links everywhere
