### ISSUE TITLE
Migrate dev branch to .NET 4.5

### ISSUE THREAD

**Issue by shatl** [sharparchitecture/Sharp-Architecture#113]
Migrate **develop** branch to .NET 4.5

**Comment by shatl** [comment]
@seif I completed code migration and going to update nuspecs. Since this is another braking change, should version be updated to 4.0? 
I'll create pull request in a week.

**Comment by seif** [comment]
Thanks shatl, I'll update the version numbers when I pull, I'll merge this into develop along with other pull request you opened for GetHashCode performance and up to 4.0

**Comment by shatl** [comment]
Hi Seif,
could you check pull request, please?

Regards,
  Vitaliy

**Comment by seif** [comment]
@shatl will do
