### ISSUE TITLE
sharp-architecture via NuGet

### ISSUE THREAD

**Issue by arifov** [sharparchitecture/Sharp-Architecture#115]
Hi! I can't install NuGet package sharp-architecture.
It errors:

Attempting to resolve dependency 'SharpArch.Domain (> 3.0.0 && < 4.0.0)'.
Unable to resolve dependency 'SharpArch.Domain (> 3.0.0 && < 4.0.0)'.

**Comment by shatl** [comment]
Yep, sharp-architecture nuspec package has wrong version reference.
As a workaround just install SharpArch.Doman, SharpArch.Nhibernate and SharpArch.Web.Mvc.Castle separately.

@seif Please update sharp-architecture.nuspec to refer versions 
as version="[3.0.0,4.0.0)" not "(3.0.0,4.0.0)"

**Comment by seif** [comment]
Thanks, pushed the fix suggested by @shatl

**Comment by arifov** [comment]
Thanks! Is NuGet package updated and ready for download?

**Comment by seif** [comment]
Yeah, new packages are published


Apologies in advance for any auto correction or spelling mistakes, sent
from my phone.
