### ISSUE TITLE
Move Sample apps to Sharp architecture repository 

### ISSUE THREAD

**Issue by seif** [sharparchitecture/Sharp-Architecture#117]
SharpArch.TardisBank (and the RavenDB branch into a seperate app)
- [x] Migrate TardisBank to Samples directory
- [x] Upgrade TardisBank/NHibernate to .NET45 and latest SharpArch and dependencies
- [ ] Upgrade TardisBank/RavenDb

**Comment by shatl** [comment]
Will create separate issue for RavenDB
