### ISSUE TITLE
NHibernate debug

### ISSUE THREAD

**Issue by arifov** [sharparchitecture/Sharp-Architecture#118]
Hi. I've faced with Oracle connection issue and i cannot understand the source of the issue.

SharpArchitecture hides NHibernate exceptions so I have only {"An ISessionStorage has not been configured"} And I cannot find the way to obtain more information.
Please help me because it makes me crazy..

Thanks.

**Comment by seif** [comment]
Sharp Architecture shouldn't be hiding nhibernate exceptions. That error means that you have not initialised correctly. What is your initialisation code?

Have a look here for an example:
https://github.com/sharparchitecture/Sharp-Architecture-Cookbook/blob/master/Solutions/SharpArchCookbook.Web.Mvc/Global.asax.cs

**Comment by arifov** [comment]
You gave me good clue and my problem is solved now. Thanks!
