### ISSUE TITLE
Source file ..\..\Common\AssemblyVersion.cs could not be found

### ISSUE THREAD

**Issue by mattcowen** [sharparchitecture/Sharp-Architecture#122]
Got the latest from github but can't compile the SA solution due to this error on 

SharpArch.Web.Mvc
SharpArch.RavenDb
SharpArch.NHibernate
SharpArch.Testing.NUnit
SharpArch.Specifications
SharpArch.Tests
SharpArch.Domain
SharpArch,Wcf
SharpArch.WcfClient.Castle

If someone tells me what should be in the Common\AssemblyVersion.cs file I will sort it out and submit a PR...

Thanks
Matt

**Comment by shatl** [comment]
Hi Matt,
Have you followed instructions from readme.txt? 
(you should run build.cmd from ./Build/ folder)
