### ISSUE TITLE
Remove Command processing code

### ISSUE THREAD

**Issue by shatl** [sharparchitecture/Sharp-Architecture#124]
Remove Command/Query code from S#Arch;
Update Samples to use https://github.com/jbogard/MediatR.

Related to #86

**Comment by crwagner** [comment]
there's no templifies for actual and newer versions of S#arp??

2015-11-24 15:17 GMT-02:00 Vitaliy K <notifications@github.com>:

**Comment by shatl** [comment]
@crwagner No, I believe having up to date sample project is better.

**Comment by crwagner** [comment]
thanks Vitaly... I was wondering where to start with the new versions (I'm
still using 2.1 w/ templify)

oh, and sorry for question this in the wrong place

2015-11-24 15:25 GMT-02:00 Vitaliy K <notifications@github.com>:

**Comment by crwagner** [comment]
can you link me this?

2015-11-24 15:25 GMT-02:00 Vitaliy K <notifications@github.com>:
