### ISSUE TITLE
Nuget - multi-platform support

### ISSUE THREAD

**Issue by shatl** [sharparchitecture/Sharp-Architecture#146]
- [ ] .NET 4.6.
- [ ] .NET Core 1.0.

See http://www.hanselman.com/blog/ASPNET5IsDeadIntroducingASPNETCore10AndNETCore10.aspx

**Comment by seif** [comment]
I imagine it'll be a while before we can support core because we have to wait for all our dependencies to support it

**Comment by shatl** [comment]
Closed with #155
