### ISSUE TITLE
Unable to resolve dependencies constraint Newtonsoft.Json >= 7.0.1 && < 8.0.0

### ISSUE THREAD

**Issue by mattcowen** [sharparchitecture/Sharp-Architecture#149]
Seems like this has happened before. Now Newtonsoft.Json is v8.0.3 I can't update it because SharpArch.Domain has a constraint that Newtonsoft.Json must be >= 7.0.1 && <= 8.0.0. Why is there a maximum version constraint? None of my other dependencies have this. It would make life a lot easier if there was no such restriction - just the minimum.

Matt

**Comment by shatl** [comment]
Hi Matt,
Usually major version change means breaking public API changes. This constraint is used to prevent broken builds after upgrade. 

I'll upgrade dependencies and release new version soon.

**Comment by shatl** [comment]
@mattcowen Please try to upgrade to S#Arch 3.1.2
