### ISSUE TITLE
Separate write and read commands using SessionFactoryAttribute

### ISSUE THREAD

**Issue by AlexanderSysoev** [sharparchitecture/Sharp-Architecture#150]
Hello!
I use SessionFactoryAttribute in my repository to read and write enitites from one session. I want change my database to slave and master. I want write entites to master and read them from slave. Is there any approach to implement this using SessionFactoryAttribute? May be there is a better solution?

**Comment by shatl** [comment]
Hi Alex,
SessionFactoryKey will be removed in v4. 

I suggest to register named ISession instances / repositories.

Please take a look at https://github.com/sharparchitecture/Sharp-Architecture/blob/develop/Solutions/SharpArch.NHibernate/NHibernateSessionFactoryBuilder.cs and Samples/TardisBank on *develop* branch
