### ISSUE TITLE
Unable to resolve dependencies constraint Newtonsoft.Json >= 7.0.1 && < 9.0.0

### ISSUE THREAD

**Issue by asouto** [sharparchitecture/Sharp-Architecture#151]
Seems like this has happened before. Now Newtonsoft.Json is v9.0.1 I can't update it because SharpArch.Domain has a constraint that Newtonsoft.Json must be >= 7.0.1 && < 9.0.0. Why is there a maximum version constraint? None of my other dependencies have this. It would make life a lot easier if there was no such restriction - just the minimum.

Souto

**Comment by shatl** [comment]
Hi, I'll check today

**Comment by asouto** [comment]
@shatl I appreciate it

**Comment by asouto** [comment]
@shatl tks...
