### ISSUE TITLE
Support Newtonsoft.JSON v10

### ISSUE THREAD

**Issue by bradlis7** [sharparchitecture/Sharp-Architecture#158]
Currently, I'm limited on updating some other packages in my project, due to not being able to upgrade Newtonsoft.JSON.

**Comment by shatl** [comment]
Will do this week

**Comment by shatl** [comment]
@bradlis7 Please try *4.0.1-beta0001* if it will work for you, I'll release it.

**Comment by shatl** [comment]
@bradlis7 Did you had a chance to try new package ?

**Comment by bradlis7** [comment]
I probably should have stated this before, but I can't test the upgrades at this time do to other issues. Sorry for the trouble.
