### ISSUE TITLE
SharpArch.Domain.Events not available in SharpArch.Domain v4.0.1

### ISSUE THREAD

**Issue by lucaarpaia** [sharparchitecture/Sharp-Architecture#163]
I'm on a sharparc based project and trying to upgrade from 3.0.0 to v4.0.1 but I have problems related to SharpArch.Domain.Events not available anymore

> The type or namespace name 'Events' does not exist in the namespace 'SharpArch.Domain' (are you missing an assembly reference?)

Is that namespace moved to a different assembly?
thank you for answers

**Comment by shatl** [comment]
It was removed. 
Please use  https://github.com/phatboyg/GreenPipes or https://github.com/jbogard/MediatR
