### ISSUE TITLE
SharpArch.Domain nupkg only contains SharpArch.Infrastructure dll

### ISSUE THREAD

**Issue by techyian** [sharparchitecture/Sharp-Architecture#192]
Hi, I'm trying to use your latest pre-release of SharpArch.Domain and SharpArch.NHibernate. Something seems a bit off with the nupkg as it only has a dll for SharpArch.Infrastructure inside it and I can't reference the Entity class in my project.

**Comment by techyian** [comment]
This seems to have broken since alpha 38.

**Comment by shatl** [comment]
Thanks, will fix

**Comment by shatl** [comment]
Please try latest build
