### ISSUE TITLE
Add support for ASP.NET Web API

### ISSUE THREAD

**Issue by sandord** [sharparchitecture/Sharp-Architecture#52]
For example, ASP.NET Web API controllers implement System.Web.Http.IHttpController. SharpArch currently only supports controllers that implement System.Web.Mvc.IController.

**Comment by shatl** [comment]
@seif I'm going to merge .NET 4.5 changes with develop branch and update this to WebApi 2.2

**Comment by seif** [comment]
@shatl That'd be great, sounds painful though :)

**Comment by garora** [comment]
Its year 2015 and I am still struggling with same problem. I extracted the latest code but did not find above changes. Are these changes merged into master or do I need to take develop branch code?

**Comment by garora** [comment]
@sandord - can you please provide some light on this issue?

**Comment by sandord** [comment]
Hi @garora, I'm about to go on a short leave but I managed to put up this repo for you: https://github.com/sandord/SharpArchWebHttp. In it you'll find the code that I'm currently using in addition to SA3 to provide webapi support. I don't know what happened to the code in the pull request mentioned above though.

**Comment by garora** [comment]
@sandord - Thanks a lot. I am going to give it try, right now and enjoy your vacassions :+1:

**Comment by sandord** [comment]
Oh, of course you will need to be doing some component registration:

    Container.Register(
        Component
            .For<IHttpControllerActivator>()
            .ImplementedBy<Neddox.Esp.Infrastructure.Web.Http.WindsorHttpControllerActivator>()
            .LifestyleTransient());

    Container.Register(
        Component
            .For<IFilterProvider>()
            .ImplementedBy<Neddox.Esp.Infrastructure.Web.Http.WindsorFilterProvider>()
            .LifestyleTransient());

And in `Application_Start`:

    GlobalConfiguration.Configuration.DependencyResolver = new WindsorDependencyResolver(Container);

**Comment by sandord** [comment]
I'm sure I'm forgetting some details here but I have to hurry now :) Good luck.

**Comment by garora** [comment]
in Global.asax file, I am using ``` ServiceLocator.SetLocatorProvider(() => new WindsorServiceLocator(container)); ```  I tried ``` GlobalConfiguration.Configuration.DependencyResolver = new WindsorDependencyResolver(Container); ``` and getting config error. It looks like I cant use this.

**Comment by shatl** [comment]
I'm working on WebAPI example in TardisBank application. Should be ready soon.

**Comment by garora** [comment]
Good @shatl :+1:

**Comment by shatl** [comment]
@garora WebApi sample merged to develop branch

**Comment by garora** [comment]
awesome!

On Thu, Jan 7, 2016 at 8:59 PM, Vitaliy K <notifications@github.com> wrote:

> @garora <https://github.com/garora> WebApi sample merged to develop branch
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharparchitecture/Sharp-Architecture/issues/52#issuecomment-169695214>
> .
>



-- 
Thanks & Regards,
Gaurav Arora

**Comment by shatl** [comment]
Just realized that dependency scope support is not implemented. Working on it.
