### ISSUE TITLE
[NHibernate] Update Setup

### ISSUE THREAD

**Issue by alecwhittington** [sharparchitecture/Sharp-Architecture#61]
Get rid of NHibernateInitializer in favor of a Windsor Facility. This will eliminate Session Storage amongst other things, making initialization simpler.

**Comment by shatl** [comment]
Hi, any updates on this?

**Comment by shatl** [comment]
@alecwhittington I like the idea.
This would be quite useful for when using SharpArch with other framework supporting nested scopes (e.g. MassTransit, Quartz..Net).

have you done any work on this?

**Comment by seif** [comment]
Don't think any work has been done on this. Alec is out, will need to
figure out a way to handle this.

I'm on holiday flying back tomorrow, maybe we should schedule a hangout for
the weekend and discuss things? I'll email in the next 2 days.


Apologies in advance for any auto correction or spelling mistakes, sent
from my phone.

**Comment by shatl** [comment]
Yep, sounds good.
I'm in EST time zone

Regards,
  Vitaliy

**Comment by seif** [comment]
Talking with Vitaliy now, agreed to strip down to basic.

Remove the initialiser, change the way repositories work to have an ISession injected in.

The multi-database functionality (curently implemented via the SessionFactoryKeyAttribute) will be out of scope initially.

Once the changes are made, we will need to come up with a way to inject the correct the ISession from the IoC registration.

THis related to #68 #69

**Comment by seif** [comment]
Also #85
