### ISSUE TITLE
[Windsor] Make use of Facility for WCF integration

### ISSUE THREAD

**Issue by alecwhittington** [sharparchitecture/Sharp-Architecture#63]

**Comment by seif** [comment]
Delete the Wcf projects and get it over with.

**Comment by shatl** [comment]
Identify the WCF related code and decide if want to keep it.

**Comment by shatl** [comment]
@seif Did you had a chance to look at it? Seems like we can switch to Castle.WcfIntegrationFacility

**Comment by seif** [comment]
I did, got the wcf stuff working, but nhibernate integration would still
require a lot of boilerplate. This is where I got to

https://github.com/sharparchitecture/Sharp-Architecture/commits/add-northwind

**Comment by shatl** [comment]
WCF integration will not be supported in v5
