### ISSUE TITLE
IViewModelQuery

### ISSUE THREAD

**Issue by alecwhittington** [sharparchitecture/Sharp-Architecture#66]
Add IViewModelQuery<T> to SharpArch.Web.Mvc. It should have one method, Query.

**Comment by shatl** [comment]
Hi,
could you please elaborate on this?

**Comment by alecwhittington** [comment]
This was to support the Q(uery) part of CQRS. It was part of the London teams WhoCanHelpMe reference application. I do not believe we made use of the original way they did it, so this never came to be.

**Comment by shatl** [comment]
I believe this can be closed. https://github.com/Command-R/Command-R or similar libraries can be used for this.
