### ISSUE TITLE
Upgrade Northwind

### ISSUE THREAD

**Issue by alecwhittington** [sharparchitecture/Sharp-Architecture#70]
It might be a shitty example, but it shines at showing how you can work with a really bad legacy database.

**Comment by shatl** [comment]
Move Northwind and Cookbook to Samples folder under S#Architecture

**Comment by shatl** [comment]
Made it compile (not run yet).

**Comment by shatl** [comment]
Not sure if it worth to do...

**Comment by seif** [comment]
@shatl indeed, I spent a couple of days trying to get wcf working but gave up in the end. Not eager on re learning the internals of wcf.

Northwind was fiddly to start with anyways because of having to install the MS samples db.

Closing this.
