### ISSUE TITLE
Transaction attributes to use ITransactionManager

### ISSUE THREAD

**Issue by seif** [sharparchitecture/Sharp-Architecture#79]
Add ITransactionManager with implementation for RavenDB/NH

Update MVC and HTTP TransactionAttribute to have ITransactionManager injected.

And whatever changes needed to get this to work!

**Comment by shatl** [comment]
@seif, couple comments/questions:

* Currently transaction is committed in ResultExecuted. Better place is ActionExecuted to make sure  changes are persisted **before** rendering view. Besides that, accessing database from view is a bad practice.
* Executing attribute on child action (e.g. if attribute is applied at class level, not method level) will result is nested transaction which is not supported by NHibernate *please correct me if I wrong*, so child action check needs to be performed in the attribute.
