### ISSUE TITLE
Allow for NH Configuration to be manipulated before creating factory

### ISSUE THREAD

**Issue by seif** [sharparchitecture/Sharp-Architecture#85]
See #83 

We need to allow end users to provide Action<Configuration> that will be passed into FNH ExposeConfiguration method.

**Comment by shatl** [comment]
With new NHibernateSessionFactoryBuilder this can be achieved in two ways:

1) Configuration settings won't be cached with UseConfigurationCache()
``
var config = nHibernateSessionFactoryBuilder.BuildConfiguration();
// manipulate configuration settings
ISessionFactory factory = nHibernateSessionFactoryBuilder.BuildSessionFactory();
``

2) Using FluentNHibernate - changes will be saved in cache 
``
var config = nHibernateSessionFactoryBuilder.UsePersistenceConfigurer(configurer;
// manipulate configuration settings
ISessionFactory factory = nHibernateSessionFactoryBuilder.BuildSessionFactory();
``
