### ISSUE TITLE
CommandProcessor ignores handler with a TResult

### ISSUE THREAD

**Issue by seif** [sharparchitecture/Sharp-Architecture#86]
Just looking at the code in https://github.com/sharparchitecture/Sharp-Architecture/blob/1197484f9e4f9ab9b84fdaa0c59045f92f084fd4/Solutions/SharpArch.Domain/Commands/CommandProcessor.cs#L13-L27
and
https://github.com/sharparchitecture/Sharp-Architecture/blob/1197484f9e4f9ab9b84fdaa0c59045f92f084fd4/Solutions/SharpArch.Domain/Commands/CommandProcessor.cs#L33

I think there would be a problem where if the caller didn't care about the result, and just wanted to fire the command and there was a handler registered for the command but implementing ICommandHandler<in TCommand, out TResult>, then that handler would not be called.

Do we want it to be called? What should we do for the other way around? where the user cared for the result and called the overload with the TResult, handlers that implement the ICommandHandler<in TCommand> would not be triggered, should they be called but without adding any result to the return Enumeration?

**Comment by seif** [comment]
And add docs for command processing/dispatching and event handling.

**Comment by shatl** [comment]
I'd rather replace command processor with https://github.com/jbogard/MediatR.
For current version we can mark it as obsolete. 
@seif,  What do you think?

**Comment by seif** [comment]
@shatl sorry for late reply, was on holiday and then needed to look at the code for MediatR and see what it does.

I was worried about that the async stuff is actually spinning up tasks, but it leaves that to the implementors. The only issue I see is the lack of a Send that doesn't have a reply. i.e. MediatR only handles the event publishing and request/response style not a trigger of a command or a Send<TRequest> without a response.

Ignore the above, did some more digging in the code, and saw https://github.com/jbogard/MediatR/blob/master/src/MediatR/Unit.cs and the abstract class of RequestHandler we'd need to use that in an example for TResponse showing how to use the mediator with it.

I don't see a reason why not to depend on it, it doesn't have any dependencies that would conflict with ours. :)

**Comment by shatl** [comment]
@seif, I believe we can close the issue then. For users who want to use Command/Query pattern, let's recommend https://github.com/jbogard/MediatR .

**Comment by seif** [comment]
Sure, wanna raise a ticket to delete the command processing code?
