### ISSUE TITLE
Remove dependency on Iesi.Collections from Mvc project

### ISSUE THREAD

**Issue by seif** [sharparchitecture/Sharp-Architecture#89]
SharpModelBinder.IsSimpleGenericBindableEntityCollection check if the property type is ISet from Iesi.Collections, this introduces a dependency on Iesi.Collections for any persistance.

Should move that check into NH specific assembly and use ModelBinder depending on persistance.

Or hopefully by the time 3.0 is ready, NH will have switched to using the .Net4 ISet and we can just remove the reference to Iesi

**Comment by shatl** [comment]
Closed in #109
