### ISSUE TITLE
Machine Spec tests failing

### ISSUE THREAD

**Issue by scpeterson** [sharparchitecture/Sharp-Architecture#93]
Once I got my Machine Spec harness working, I found that 13 specification tests are failing in the v3 branch in the file HasUniqueDomainSignatureSpecs.cs:

when_validating_a_duplicate_entity_with_no_error_message_specified
when_validating_a_duplicate_entity_with_a_specified_error_message
when_validating_an_entity_with_a_guid_id_and_a_duplicate_exists
when_validating_an_entity_and_a_duplicate_exists
when_validating_a_duplicate_entity_that_has_a_value_object_domain_signature_property
when_validating_an_entity_with_a_string_id_and_a_duplicate_exists
when_validating_a_duplicate_entity_that_has_a_null_value_domain_signature_property
When_validating_duplicate_entity_that_has_null_value_for_property_of_unique_entity_type
when_validating_a_duplicate_entity_that_has_another_entity_as_part_of_domain_signature
when_validating_a_unique_entity_that_has_another_entity_as_part_of_domain_signature
when_validating_an_entity_and_the_entity_is_unique
when_validating_a_unique_entity_that_has_a_null_value_domain_signature_property
When_validating_duplicate_entity_that_has_null_value_for_property_of_unique_entity_type

The error message is the same for all these: "An ISessionStorage has not been configured."

I tracked down where the problem appears to occur, in the NHibernateSession.cs file on line 386: if (File.Exists("Hibernate.cfg.xml"))

This line always returns false, even though Hibernate.cfg.xml is properly copied over to bin\debug.  If I change the line to: (File.Exists(AppDomain.CurrentDomain.BaseDirectory + "\\Hibernate.cfg.xml"))
then everything works just fine and the tests pass.   Shouldn't File.Exists pick up on the fact that the file is there, in the same directory as the process?  Is it really necessary to specify the whole path?  My change worked, but it doesn't seem like I should have to make the change.  Any thoughts are welcome...

**Comment by shatl** [comment]
not failing anymore
