### ISSUE TITLE
Restore nuget packages before starting build

### ISSUE THREAD

**Issue by seif** [sharparchitecture/Sharp-Architecture#96]
Build failed on teamcity due to Bcl nuget package.

Check http://blogs.msdn.com/b/dotnet/archive/2013/08/12/improved-package-restore.aspx for more details.

For the time being, added a teamcity build step to restore the packages, but this is not ideal as someone checking out the code and trying to build will fail the first time.

**Comment by shatl** [comment]
@seif This will be addressed by .NET 4.5 migration. Please assign this to me.

**Comment by shatl** [comment]
This is fixed by .NET 4.5 migration
